# Test against the latest version of this Node.js version
environment:
  nodejs_version: "11"

# Test on all arch
platform:
  - x86
  - x64
  - Any CPU

# Supported OSes
image:
  - Visual Studio 2015
  - Ubuntu

# A failure in any job fails all.
matrix:
  fast_finish: true


# Install scripts. (runs after repo cloning)
install:
  # Load all submodules
  - git submodule update --init --recursive
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run prettilint
  
build_script:
  - npm run build
  
