# Test against the latest version of this Node.js version
environment:
  nodejs_version: "11"
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  NPM_CONFIG_LOGLEVEL: "error"
  NODE_VERBOSE: "false"

cache: 
  - node_modules

# Don't duplicate things
skip_branch_with_pr: true

# Test on all arch
platform:
  - x86
  - x64

# Supported OSes
image:
  - Ubuntu1804
  - Visual Studio 2015

# A failure in any job fails all.
matrix:
  fast_finish: true


# Install scripts. (runs after repo cloning)
install:
  # Load all submodules
  - ps: Install-Product node $env:nodejs_version
  - sh: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash && nvm install node && node --version
  - git submodule update --init --recursive
  # Don't show progress on CI
  - npm set progress=false
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run prettilint
  
build_script:
  - sh: set HESTIA_VERSION=$(node -e "console.log(require('./package.json').version);")
  - cmd: >-
        node -e "console.log(require('./package.json').version);" > HESTIA_VERSION.txt
        set /p HESTIA_VERSION=<HESTIA_VERSION.txt
  - npm run build
  
artifacts:
  - path: build
    name: Hestia (Testing build) - $(HESTIA_VERSION).{branch}
